using CDA.Models;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CDA.Controllers
{
    public class VolController : Controller
    {
        private readonly IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "4ziVxinSXVTinYwMpcjIFtS8n2wwN6ER0C9Y5C81",
            BasePath = "https://tp-company-aerienne-default-rtdb.europe-west1.firebasedatabase.app/"
        };

        private IFirebaseClient client;

        public VolController()
        {
            client = new FireSharp.FirebaseClient(config);
        }

        // GET: VolController
        public ActionResult Index()
        {
            FirebaseResponse response = client.Get("Vols");
            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
            var list = new List<Vol>();
            if (data != null)
            {
                foreach (var item in data)
                {
                    list.Add(JsonConvert.DeserializeObject<Vol>(((JProperty)item).Value.ToString()));
                }
            }
            return View(list);
        }

        // GET: VolController/Details/5
        public ActionResult Details(string id)
        {
            FirebaseResponse response = client.Get($"Vols/{id}");
            Vol vol = JsonConvert.DeserializeObject<Vol>(response.Body);
            return View(vol);
        }

        // GET: VolController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VolController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Vol vol)
        {
            try
            {
                PushResponse response = client.Push("Vols/", vol);
                vol.VolId = response.Result.name; // VolId will be auto generated by Firebase
                client.Set($"Vols/{vol.VolId}", vol);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(vol);
            }
        }

        // GET: VolController/Edit/5
        public ActionResult Edit(string id)
        {
            FirebaseResponse response = client.Get($"Vols/{id}");
            Vol vol = JsonConvert.DeserializeObject<Vol>(response.Body);
            return View(vol);
        }

        // POST: VolController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, Vol vol)
        {
            try
            {
                client.Update($"Vols/{id}", vol);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(vol);
            }
        }

        // GET: VolController/Delete/5
        public ActionResult Delete(string id)
        {
            FirebaseResponse response = client.Get($"Vols/{id}");
            Vol vol = JsonConvert.DeserializeObject<Vol>(response.Body);
            return View(vol);
        }

        // POST: VolController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, IFormCollection collection)
        {
            try
            {
                client.Delete($"Vols/{id}");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}
